# Generated by Django 6.0 on 2025-12-04 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura (°C)'), ('humedad', 'Humedad (%)'), ('luz', 'Iluminación (lux)')], max_length=20)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='monitoreo.municipio')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
